name: 'My curriculum vitae'
description: 'Pushing to GitHub repository local changes'
author: 'stefanos1316'
inputs:
  github_token:
    description: 'Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}'
    required: true
  repository:
    description: 'Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})'
    default: ''
    required: false
  branch:
    description: 'Destination branch to push changes'
    required: false
    default: 'gh-pages'
  force:
    description: 'Determines if force push is used'
    required: false
  tags:
    description: 'Determines if --tags is used'
    required: false
  directory:
    description: 'Directory to change to before pushing.'
    required: false
    default: '.'
runs:
  using: 'node12'
  main: 'start.js'
