# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt-get install texlive-xetex texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-context pandoc
        pip install "notebook==4.1" requests jupyter_cms jupyter_dashboards
    - name: Make new content
      run: |
        make
    - name: Commit files
      run: |
        git checkout gh-pages
        git config user.name stefanos1316
        git config user.email stefanos1316@gmail.com
        git add web/*
        git commit -m "New site fixes - $(date)"
    - name: Deploy changes
      uses: stefanos1316/my_curriculum_vitae@gh-pages
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
